export default  [
  {'ba.chm-cbd.net': 'bih-chm-cbd.ba'},
  {'sc.chm-cbd.net':'seychellesbiodiversitychm.sc'},
  {'cn.chm-cbd.net':'english.biodiv.gov.cn'},
  {'iq.chm-cbd.net':'moen.gov.iq'},
  {'jp.chm-cbd.net':'www.biodic.go.jp'},
  {'my.chm-cbd.net':'www.mybis.gov.my'},
  {'mm.chm-cbd.net':'www.myanmarchm.gov.mm/en_US'},
  {'kr.chm-cbd.net':'www.cbd-chm.go.kr'},
  {'by.chm-cbd.net':'biodiv.by'},
  {'hr.chm-cbd.net':'www.bioportal.hr'},
  {'cz.chm-cbd.net':'chm.nature.cz'},
  {'ee.chm-cbd.net':'chm.eionet.europa.eu/chm_ee'},
  {'hu.chm-cbd.net':'www.biodiv.hu'},
  {'pl.chm-cbd.net':'biodiv.gdos.gov.pl'},
  {'ru.chm-cbd.net':'www.ruschm.ru'},
  {'rs.chm-cbd.net':'biodiverzitet-chm.rs'},
  {'si.chm-cbd.net':'chm.zrsvn.si'},
  {'do.chm-cbd.net':'www.ambiente.gob.do'},
  {'gd.chm-cbd.net':'gd.chm-cbd.net'},
  {'jm.chm-cbd.net':'jamaicachm.org.jm/CHM'},
  {'mx.chm-cbd.net':'www.biodiversidad.gob.mx'},
  {'au.chm-cbd.net':'www.environment.gov.au/biodiversity'},
  {'at.chm-cbd.net':'www.biodiv.at'},
  {'ad.chm-cbd.net':'www.mediambient.ad/biodiversitat'},
  {'eu.chm-cbd.net':'biodiversity.europa.eu'},
  {'fi.chm-cbd.net':'www.biodiversity.fi'},
  {'nl.chm-cbd.net':'en.biodiversiteit.nl'},
  {'se.chm-cbd.net':'www.naturvardsverket.se/cbd'},
  {'at.chm-cbd.net':'www.biologischevielfalt.at'},
  {'cu.chm-cbd.net':'www.ecosis.cu'},
  {'kh.chm-cbd.net':'chm-ncsd.moe.gov.kh'},
]// 

