export const focalPoints = [

  {
      id:  "6789",
      email: "Klodiana.Marika@turizmi.gov.al",
      lastName: "Marika",
      firstName: "Klodiana",
      country: "al",
      categoryList: "CBD-FP1 CHM-FP CBD-NR SBSTTA-FP CPB-FP1 CPB-A17-FP BCH-FP RM-FP",
      prefix: "Mrs.",
      position: "Director",
      department: "Department of Biodiversity and Protected Areas",
      organizationName: "Ministry of Tourism and Environment",
      phone: "+355 692092872",
      organizationUrl: "http://www.mjedisi.gov.al/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1694",
      email: "chenoufnadia@yahoo.fr",
      lastName: "Chenouf",
      firstName: "Nadia",
      country: "dz",
      categoryList: "CBD-FP1 CHM-FP CBD-NR SBSTTA-FP",
      prefix: "Mlle.",
      position: "Directrice de l'Evaluation des études environnementales",
      organizationName: "Ministère de l'Environnement et des Énergies Renouvelables",
      phone: "+213 21 43 2884",
      unLang: "AR-FR-EN",
      mailOutLang: "AF"
  },
  {
      id:  "1212",
      email: "dcblack11@gmail.com",
      "E-Mail 2": "dcblack11@yahoo.com",
      "E-Mail 3": "antiguaenvironmentdivision@gmail.com",
      lastName: "Black-Layne",
      firstName: "Diann",
      country: "ag",
      categoryList: "CBD-FP1 CHM-FP CBD-NR ABS-FP CPB-FP1 CPB-A17-FP PA-FP GTI-FP RM-FP IND-EG",
      prefix: "Ms.",
      position: "Chief Environment Officer",
      department: "Environment Division",
      organizationName: "Ministry of Health, Wellness and the Environment",
      phone: "+1 268 462 4625, 1 268 562 2568",
      organizationUrl: "www.environmentdivision.info",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7229",
      email: "dfs@ambiente.gob.ar",
      "E-Mail 2": "sdalessio@ambiente.gob.ar",
      lastName: "D'Alessio",
      firstName: "Santiago",
      country: "ar",
      categoryList: "CHM-FP CEPA-IAC SBSTTA-FP GSPC-FP",
      prefix: "Lic.",
      position: "Director de Fauna Silvestre y Biodiversidad",
      organizationName: "Ministerio de Ambiente y Desarrollo Sustentable",
      phone: "+54 11 4348 8550",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "6517",
      email: "CBDAustralia@awe.gov.au",
      lastName: "Miller",
      firstName: "Kat",
      country: "au",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP TKBD-FP PA-FP RM-FP",
      prefix: "Ms.",
      position: "Director",
      department: "Biodiversity Policy Section",
      organizationName: "Department of Agriculture, Water and the Environment",
      phone: "+61 2 6274 2711",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1889",
      email: "martin.goetzl@umweltbundesamt.at",
      lastName: "Gotzl",
      firstName: "Martin",
      country: "at",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Dr.",
      organizationName: "Federal Environment Agency",
     phone: "+43 1 31304 3380",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1459",
      email: "rochellenewbold@bahamas.gov.bs",
      "E-Mail 2": "rwnewbold@depp.gov.bs",
      lastName: "Newbold",
      firstName: "Rochelle W.",
      country: "bs",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP CPB-FP1 CPB-A17-FP BCH-FP GTI-FP GSPC-FP",
      prefix: "Mrs.",
      position: "Director",
      department: "Department of Environmental Planning and Protection",
      organizationName: "Ministry of the Environment and Housing",
     phone: "+1 242 322 4546",
      organizationUrl: "http://www.best.gov.bs/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6719",
      email: "nalwasmi@sce.gov.bh",
      lastName: "Ali Al-Wasmi",
      firstName: "Nouf",
      country: "bh",
      categoryList: "CBD-FP1 CHM-FP CBD-NR CPB-FP1 CPB-A17-FP BCH-FP PA-FP",
      prefix: "Ms.",
      position: "Senior Environmental Specialist",
      organizationName: "Supreme Council for Environment",
     phone: "+973 17386582",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "7468",
      email: "secretary@moef.gov.bd",
      lastName: "Hasan ndc",
      firstName: "Ziaul",
      country: "bd",
      categoryList: "CBD-FP1 CHM-FP CPB-FP1 BCH-FP",
      prefix: "Mr.",
      position: "Secretary",
      organizationName: "Ministry of Environment, Forest and Climate Change",
     phone: "+880 2 9540481",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6377",
      email: "marcia.kirton@barbados.gov.bb",
      "E-Mail 2": "kim.downesagard@barbados.gov.bb",
      lastName: "Kellman",
      firstName: "Daphne",
      country: "bb",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP CPB-FP1 BCH-FP",
      prefix: "Ms.",
      position: "Permanent Secretary",
      organizationName: "Ministry of Environment and National Beautification",
     phone: "+1 246 535 4354",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6944",
      email: "svidzinski.bio@gmail.com",
      lastName: "Svidzinski",
      firstName: "Mikalai",
      country: "by",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP CPB-FP1 PA-FP",
      prefix: "Mr.",
      position: "Head",
      department: "Department of Biological and Landscape Diversity",
      organizationName: "Ministry of Natural Resources and Environmental Protection",
     phone: "+375 17 200 66 91",
      organizationUrl: "http://www.ecoinfo.by/content/49.html?language=24",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "2453",
      email: "hdekoeijer@naturalsciences.be",
      "E-Mail 2": "cbd-chm@naturalsciences.be",
      lastName: "de Koeijer",
      firstName: "Han",
      country: "be",
      categoryList: "CHM-FP CHM-IAC CHM-NET CEPA-IAC ABSCH-PA",
      prefix: "Mr.",
      position: "CHM NFP",
      department: "Department of Invertebrates",
      organizationName: "Royal Belgian Institute of Natural Sciences",
     phone: "+32 2 627 42 67",
      unLang: "FR-EN",
      mailOutLang: "E"
  },
  {
      id:  "4157",
      email: "officer2.nbio@environment.gov.bz",
      "E-Mail 2": "GarciaRA@gobmail.gov.bz",
      lastName: "Garcia",
      firstName: "Rasheda",
      country: "bz",
      categoryList: "CBD-FP2 CHM-FP",
      prefix: "Ms.",
      department: "National Biodiversity Office",
      organizationName: "Ministry of Fisheries, Forestry, the Environment and Sustainable Development",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6519",
      email: "charles.shulman@canada.ca",
      lastName: "Shulman",
      firstName: "Charles",
      country: "ca",
      categoryList: "CHM-FP CHM-IAC",
      prefix: "Mr.",
      position: "Senior Policy Advisor",
      department: "Canadian Wildlife Service",
      organizationName: "Environment and Climate Change Canada",
     phone: "+1 819 938 4064",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7405",
      email: "moehamachantal@yahoo.fr",
      lastName: "Moehama Banga",
      firstName: "Chantal",
      country: "cf",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Chef de Service da la Communication",
      organizationName: "Ministère de l’Environnement et du Développement durable",
     phone: "+236 75 50 55 48",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7666",
      email: "mikerbysaleh@gmail.com",
      lastName: "Mikherbi",
      firstName: "Saleh Moussa",
      country: "td",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP",
      prefix: "M.",
      organizationName: "Ministère de l'Environnement et de la Pêche",
     phone: "+235 63 69 03 04",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6635",
      email: "kmolt@mma.gob.cl",
      "E-Mail 2": "movalle@mma.gob.cl",
      lastName: "Molt González",
      firstName: "María Karin",
      country: "cl",
      categoryList: "CHM-FP RM-FP",
      prefix: "Sra.",
      position: "Jefa, Departamento de Politicas y Planificacion de la Biodiversidad",
      department: "División de Recursos Naturales y Biodiversidad",
      organizationName: "Ministerio del Medio Ambiente",
     phone: "+56 22 573 5695",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "3966",
      email: "jing.xin@mee.gov.cn",
      lastName: "Jing",
      firstName: "Xin",
      country: "cn",
      categoryList: "CHM-FP CHM-IAC SBSTTA-FP ABS-FP CPB-A17-FP BCH-FP TKBD-FP PA-FP GSPC-FP",
      prefix: "Ms.",
      position: "Director, Division of Biodiversity Conservation",
      department: "Department of Nature and Ecology Conservation",
      organizationName: "Ministry of Ecology and Environment",
     phone: "+86 10 6564 5432",
      unLang: "ZH-EN",
      mailOutLang: "C"
  },
  {
      id:  "5997",
      email: "hgarcia@humboldt.org.co",
      "E-Mail 2": "secretariadireccion@humboldt.org.co",
      "E-Mail 3": "lbermudez@minambiente.gov.co",
      "E-Mail 4": "mlaverde@minambiente.gov.co",
      lastName: "Garcia",
      firstName: "Hernando",
      country: "co",
      categoryList: "CHM-FP",
      prefix: "Sr.",
      position: "Director General",
      organizationName: "Instituto de Investigación de Recursos Biológicos Alexander Von Humboldt",
     phone: "+571 320 2767 ext 1101, 1112",
      organizationUrl: "http://chmcolombia.co/",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "5953",
      email: "sittraissat@yahoo.fr",
      lastName: "Mohamed",
      firstName: "Raissat",
      country: "km",
      categoryList: "CHM-FP",
      prefix: "Mlle",
      department: "Direction Générale de l'Environnement et des Forêts",
      organizationName: "Ministère de l'Agriculture, de la Pêche et de l'Environnement",
     phone: "+269 339 50 21",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "1172",
      email: "maclave10@gmail.com",
      lastName: "Gaentsa",
      firstName: "Romaric Maclave",
      country: "cg",
      categoryList: "CHM-FP",
      prefix: "M.",
      position: "Administrateur des SAF de 1ère classe",
      organizationName: "Ministère du Tourisme et de l'Environnement",
     phone: "+242 06 644 90 37",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7429",
      email: "nga.puna@cookislands.gov.ck",
      "E-Mail 2": "secfa@cookislands.gov.ck",
      lastName: "Puna",
      firstName: "Nga",
      country: "ck",
      categoryList: "CHM-FP ABS-FP PA-FP",
      prefix: "Mr.",
      position: "Director",
      department: "National Environment Service",
     phone: "+682 21 256",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7260",
      email: "genuar.nunez@conagebio.go.cr",
      lastName: "Román Nuñez Vega",
      firstName: "Genuar",
      country: "cr",
      categoryList: "CHM-FP",
      prefix: "Sr.",
      position: "Funcionario",
      organizationName: "Oficina Técnica de la Comisión para the Gestión de la Biodiversidad (CONAGEBIO)",
     phone: "+506 2234 12 54 ext 125",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "1145",
      email: "bernard_koffi@hotmail.com",
      lastName: "Koffi",
      firstName: "Yao Bernard",
      country: "ci",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Chef de Service des Etudes",
      department: "Direction de l'Environnement",
      organizationName: "Ministère de l’Environnement et du Développement Durable",
     phone: "+225 20 21 9709, +225 20 21 0623",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "4883",
      email: "ramona.topic@mingor.hr",
      lastName: "Topić",
      firstName: "Ramona",
      country: "hr",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Senior Advisor - Specialist, Section for Appropriate Assessment Service for Ecological Network and Sustainability of Natural Resource Use",
      department: "State Institute for Nature Protection",
      organizationName: "Ministry of Economy and Sustainable Development",
     phone: "+385 1 5502 929",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3313",
      email: "ulises@citma.gob.cu",
      "E-Mail 2": "jesus@citma.gob.cu",
      "E-Mail 3": "jesusgb@ceniai.inf.cu",
      lastName: "Fernández Gómez",
      firstName: "Ulises",
      country: "cu",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP CPB-FP1 GTI-FP RM-FP GSPC-FP",
      prefix: "Mr.",
      position: "Director, International Relations",
      organizationName: "Ministry of Science, Technology and Environment",
     phone: "+53 5 214 4554",
      organizationUrl: "http://www.cubagob.cu/",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "7315",
      email: "sedjro11@gmail.com",
      lastName: "Assogba",
      firstName: "Amandine",
      country: "bj",
      categoryList: "CHM-FP",
      prefix: "M.",
      position: "Ingénieur des Eaux, Forêts et Chasse",
      department: "Officier Conservateur des Eaux, Forêts et Chasse",
      organizationName: "Ministère du Cadre de Vie et du Développement Durable",
     phone: "+229 97518572",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7316",
      email: "yabicc@yahoo.fr",
      "E-Mail 2": "yabicc@gmail.com",
      lastName: "Yabi",
      firstName: "Chaffra Charles",
      country: "bj",
      categoryList: "CHM-FP",
      prefix: "M.",
      organizationName: "Ministère du Cadre de Vie et du Développement Durable",
     phone: "+22997195515, +22995450474",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "1255",
      email: "sonamlk@nec.gov.bt",
      lastName: "Khandu",
      firstName: "Sonam Lhaden",
      country: "bt",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP PA-FP GTI-FP GSPC-FP",
      prefix: "Ms.",
      position: "Chief Environment Officer",
      department: "Biodiversity and Land Use",
      organizationName: "National Environment Commission",
     phone: "+975 2 323 384",
      organizationUrl: "http://www.nec.gov.bt/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7021",
      email: "enzo.aliaga@mmaya.gob.bo",
      "E-Mail 2": "vmabolivia@gmail.com",
      "E-Mail 3": "ealiaga@hotmail.com",
      "E-Mail 4": "maria.cuellar@mmaya.gob.bo",
      lastName: "Aliaga Rossel",
      firstName: "Enzo Ronald",
      country: "bo",
      categoryList: "CBD-FP2 CHM-FP SBSTTA-FP BCH-FP TKBD-FP PA-FP GTI-FP GSPC-FP",
      prefix: "Dr.",
      position: "Director de Biodiversidad y Áreas Protegidas",
      department: "Viceministerio de Medio Ambiente, Biodiversidad, Cambiós Climáticos y de Gestión y Desarrollo Forestal - Dirección General de Biodiversidad y Áreas Protegidas",
      organizationName: "Ministerio de Medio Ambiente y Agua",
     phone: "+591 2 2146382, +591 2 2146385, +591 2 119966, +591 2 118582",
      organizationUrl: "http://www.mmaya.gob.bo",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "7421",
      email: "alfredy.alvarez@mmaya.gob.bo",
      lastName: "Álvarez Saavedra",
      firstName: "Alfredy Guillermo",
      country: "bo",
      categoryList: "CBD-FP1 CHM-FP TKBD-FP PA-FP GTI-FP GSPC-FP",
      prefix: "Ing.",
      position: "Viceministro de Medio Ambiente, Biodiversidad, Cambiós Climáticos y\r\nde Gestión y Desarrollo Forestal",
      organizationName: "Ministerio de Medio Ambiente y Agua",
     phone: "+591 2 214 63 82, +591 2 214 63 85, +591 2 212 43 21",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "6275",
      email: "dkgaodi@gov.bw",
      "E-Mail 2": "dikeme@gmail.com",
      lastName: "Kgaodi",
      firstName: "Dikeme",
      country: "bw",
      categoryList: "CHM-FP ABSCH-PA",
      prefix: "Mr.",
      position: "Principal Natural Resources Officer",
      department: "Department of Environmental Affairs",
      organizationName: "Ministry of Environment, Natural Resources Conservation and Tourism",
     phone: "+267 390 2050",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "4031",
      email: "nmihaylova@moew.government.bg",
      "E-Mail 2": "chmbg@moew.government.bg",
      lastName: "Mihaylova",
      firstName: "Nadya",
      country: "bg",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mrs.",
      position: "Expert, Protected Areas Division",
      department: "National Nature Protection Service Directorate",
      organizationName: "Ministry of Environment and Water",
     phone: "+359 2 940 66 11",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6521",
      email: "mloari@yahoo.fr",
      "E-Mail 2": "mlouari@gmail.com",
      lastName: "Louari",
      firstName: "Robert Madja",
      country: "bf",
      categoryList: "CHM-FP",
      prefix: "M.",
      organizationName: "Ministère de l'Environnement, de l'Économie Verte et du Changement climatique",
     phone: "+226 50 31 24 64",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7326",
      email: "obpe_burundi@obpe.bi",
      "E-Mail 2": "hatungimanaberchmans@yahoo.fr",
      lastName: "Hatungimana",
      firstName: "Berchmans",
      country: "bi",
      categoryList: "CBD-FP1 CHM-FP",
      prefix: "Mr.",
      position: "Directeur général",
      organizationName: "Office Burundais pour la Protection de l'Environnement (OBPE)",
     phone: "+257 79 81 24 77",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "3265",
      email: "somalychan.ca@gmail.com",
      lastName: "Chan",
      firstName: "Somaly",
      country: "kh",
      categoryList: "CHM-FP CHM-NET ABS-FP ABSCH-PA PA-FP GSPC-FP",
      prefix: "Ms.",
      position: "Deputy Secretary General",
      department: "National Council for Sustainable Development",
      organizationName: "Ministry of Environment",
     phone: "+855 23 6445 222, +855 12 457 799",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7247",
      email: "mfantasylvie@yahoo.com",
      "E-Mail 2": "fasyle@yahoo.fr",
      lastName: "Sylvie",
      firstName: "Fanta",
      country: "cm",
      categoryList: "CHM-FP",
      prefix: "Mrs.",
      position: "Head of CHM Unit",
      department: "Center for Documentation and Environmental Information",
      organizationName: "Ministry of Environment, Protection of Nature and Sustainable Development",
      phone: "+237 699 081 406",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "5934",
      email: "estylianopoulou@environment.moa.gov.cy",
      "E-Mail 2": "mhadjistylli@environment.moa.gov.cy",
      lastName: "Stylianopoulou",
      firstName: "Elena",
      country: "cy",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR ABS-FP CPB-FP1 BCH-FP",
      prefix: "Mrs.",
      position: "Senior Environment Officer",
      department: "Department of Environment",
      organizationName: "Ministry of Agriculture, Rural Development and Environment",
      phone: "+357 22408929",
      organizationUrl: "www.moa.gov.cy/environment",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1158",
      email: "jan.plesnik@nature.cz",
      "E-Mail 2": "janplesnik@hotmail.com",
      lastName: "Plesnik",
      firstName: "Jan",
      country: "cz",
      categoryList: "CHM-FP SBSTTA-FP",
      prefix: "Dr.",
      position: "Head",
      department: "Unit of International Cooperation",
      organizationName: "Agency for Nature Conservation and Landscape Protection",
     phone: "+420 283 069 246",
      organizationUrl: "http://www.nature.cz",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1830",
      email: "shkwak@unicef.org",
      country: "kp",
      categoryList: "CHM-FP CHM-NET",
      organizationName: "National Coordinating Committee for the Environment (NCCE)",
     phone: "+850 2 381 8370, +850 2 18111",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3267",
      email: "gmbokan@gmail.com",
      lastName: "Mboma Akani",
      firstName: "Guy",
      country: "cd",
      categoryList: "CHM-FP CHM-NET CPB-FP1 BCH-FP",
      prefix: "M.",
      department: "Direction du Développement Durable",
      organizationName: "Ministère de l'Environnement et Développement Durable",
     phone: "+243 899 459 376",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6416",
      email: "krkvi@mim.dk",
      "E-Mail 2": "mim@mim.dk",
      lastName: "Kvist",
      firstName: "Kristian",
      country: "dk",
      categoryList: "CBD-FP1 CHM-FP CBD-NR SBSTTA-FP ABSCH-PA RM-FP GSPC-FP",
      prefix: "Mr.",
      position: "Head of Section",
      department: "Nature and Climate Adaption",
      organizationName: "Ministry of Environment",
     phone: "+45 20 69 99 51, +45 38 14 21 42",
      organizationUrl: "http://eng.naturstyrelsen.dk/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6403",
      email: "metade@intnet.dj",
      "E-Mail 2": "dini_omar@yahoo.fr",
      "E-Mail 3": "med.environnement_dj@yahoo.fr",
      "E-Mail 4": "mhuecabinet@gmail.com",
      lastName: "Moussa",
      firstName: "Mohamed Abdoulkader",
      country: "dj",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP GTI-FP MIN-CBD",
      prefix: "H.E.M.",
      position: "Ministre",
      organizationName: "Ministère de l'Urbanisme, de l'Environnement et du Tourisme",
     phone: "+253 35 00 06, +253 35 83 57",
      organizationUrl: "http://www.environnement.dj/",
      unLang: "AR-FR-EN",
      mailOutLang: "AF"
  },
  {
      id:  "4409",
      email: "psagriculture@dominica.gov.dm",
      lastName: "Thomas",
      firstName: "Reginald E.",
      country: "dm",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP ABS-FP TKBD-FP GTI-FP",
      prefix: "Dr.",
      position: "Permanent Secretary (Ag)",
      organizationName: "Ministry of Blue & Green Economy, Agriculture & National Food Security",
     phone: "+1 767 266 3282, +1 767 448 2401",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1208",
      email: "Marina.Hernandez@ambiente.gob.do",
      "E-Mail 2": "recursos.geneticos@ambiente.gob.do",
      "E-Mail 3": "marina_hernandez@hotmail.com",
      lastName: "Hernández",
      firstName: "Marina",
      country: "do",
      categoryList: "CHM-FP CHM-NET CBD-NR ABS-FP ABSCH-PA CPB-FP1 BCH-FP",
      prefix: "Ms.",
      position: "Directora",
      department: "Departamento de Recursos Geneticos - Direccion de  Biodiversidad",
      organizationName: "Vice ministerio Áreas Protegidas y Biodiversidad, Ministerio de Medio Ambiente y Recursos Naturales",
     phone: "+1 809 807 1116",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "7205",
      email: "danny.guarderas@ambiente.gob.ec",
      "E-Mail 2": "fanny.tello@ambiente.gob.ec",
      lastName: "Guarderas",
      firstName: "Danny",
      country: "ec",
      categoryList: "CHM-FP GSPC-FP",
      prefix: "Sr.",
      position: "Técnico, Unidad de Vida Silvestre",
      department: "Dirección Nacional de Biodiversidad",
      organizationName: "Ministerio del Ambiente y Agua",
     phone: "+593 2 398 7600 ext 1417",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "7209",
      email: "fanny.tello@ambiente.gob.ec",
      lastName: "Tello",
      firstName: "Fanny",
      country: "ec",
      categoryList: "CHM-FP PA-FP GTI-FP GSPC-FP",
      prefix: "Sra.",
      position: "Especialista de Vida Silvestre",
      department: "Dirección de Biodiversidad",
      organizationName: "Ministerio de Ambiente y Agua",
     phone: "+593 2 398 7600 ext 1417",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "1674",
      email: "tahernbu@gmail.com",
      "E-Mail 2": "iat20000@hotmail.com",
      "E-Mail 3": "eeaa4@idsc.gov.eg",
      lastName: "Issa",
      firstName: "Taher",
      country: "eg",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Director",
      department: "Biodiversity Unit, Nature Conservation Sector",
      organizationName: "Egyptian Environmental Affairs Agency",
     phone: "+202 525 6445",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "1067",
      email: "jequezada@marn.gob.sv",
      "E-Mail 2": "jordiquebu@yahoo.es",
      lastName: "Quezada Diaz",
      firstName: "Jorge Ernesto",
      country: "sv",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR CPB-FP1 BCH-FP",
      prefix: "Dr.",
      position: "Gerente de Recursos Biológicos",
      organizationName: "Ministerio de Medio Ambiente y Recursos Naturales",
     phone: "+503 2132 9697",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "53",
      email: "engongaosono@yahoo.fr",
      lastName: "Engonga",
      firstName: "Santiago Francisco",
      country: "gq",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR BCH-FP",
      prefix: "Don",
      position: "Secretario de Estado de Medio Ambiente",
      organizationName: "Ministerio de Agricultura, Ganadería, Bosques y Medio Ambiente",
     phone: "+240 09 13 05",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "1176",
      email: "abyoze@yahoo.com",
      lastName: "Yohannes",
      firstName: "Abraham",
      country: "er",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      department: "Department of Environment",
      organizationName: "Ministry of Land, Water and Environment",
     phone: "+291 1 125887, +291 1 120311",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7259",
      email: "reigo.roasto@envir.ee",
      lastName: "Roasto",
      firstName: "Reigo",
      country: "ee",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      organizationName: "The Estonian Environmental Agency",
     phone: "+372 673 7564",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6541",
      email: "cfmhlanga@sea.org.sz",
      lastName: "Mhlanga",
      firstName: "Calisile F.",
      country: "sz",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Biodiversity Officer",
      organizationName: "Eswatini Environment Authority",
     phone: "+268 2404 7893",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7474",
      email: "befekadukt@gmail.com",
      lastName: "Kefelegn",
      firstName: "Befekadu",
      country: "et",
      categoryList: "CHM-FP CEPA-IAC",
      prefix: "Mr.",
      position: "Director for Public Relation and Communication",
      organizationName: "Ethiopian Biodiversity Institute",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7392",
      email: "brian.macsharry@eea.europa.eu",
      lastName: "Mac Sharry",
      firstName: "Brian",
      country: "eur",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Biodiversity information management Expert",
      department: "European Environment Agency",
     phone: "+45 40 38 2450",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7007",
      email: "singhsk@govnet.gov.fj",
      lastName: "Singh",
      firstName: "Sandeep",
      country: "fj",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP ABSCH-PA CPB-FP1 CPB-A17-FP BCH-FP",
      prefix: "Ms.",
      position: "Director",
      department: "Department of Environment",
      organizationName: "Ministry of Waterways and Environment",
     phone: "+679 3311699",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1123",
      email: "jukka-pekka.jappinen@ym.fi",
      "E-Mail 2": "marja.pylvanainen@ymparisto.fi",
      lastName: "Jäppinen",
      firstName: "Jukka-Pekka",
      country: "fi",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Deputy Director, Development Manager",
      department: "Biodiversity Centre, Director's Office",
      organizationName: "Finnish Environment Institute SYKE",
     phone: "+358 400 394 932",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3829",
      email: "denis.duclos@mnhn.fr",
      lastName: "Duclos",
      firstName: "Denis",
      country: "fr",
      categoryList: "CHM-FP SBSTTA-FP",
      prefix: "M.",
      position: "Directeur des relations européennes et internationales",
      organizationName: "Muséum National d'Histoire Naturelle",
     phone: "+33 1 40 79 80 46",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "1978",
      email: "scoutgabon@yahoo.fr",
      lastName: "Bayani Ngoyi",
      firstName: "Emmanuel",
      country: "ga",
      categoryList: "CBD-FP1 CHM-FP CBD-NR ABS-FP TKBD-FP",
      prefix: "M.",
      position: "Chargé d'études du Directeur général de l'environnement et de la protection de la nature",
      organizationName: "Ministère des Eaux, des Forêts, de la Mer, de l'Environnement, chargé du Plan Climat, des Objectifs de développement durable et du Plan d'affectation des terres",
     phone: "+241 04 13 07 39",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "5947",
      email: "michellemilendji@yahoo.fr",
      "E-Mail 2": "scoutgabon@yahoo.fr",
      "E-Mail 3": "mikissa_jeanbruno@yahoo.fr",
      "E-Mail 4": "jbmikissa@gmail.com",
      lastName: "Milendji Koumba, épouse Ntougou",
      firstName: "Chimène Michelle",
      country: "ga",
      categoryList: "CHM-FP BCH-FP",
      prefix: "Mme.",
      position: "Chef",
      organizationName: "Service de l'Environnement Rural et Urbain (DGEPN-MHUEDD)",
     phone: "+241 07 56 00 58",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "60",
      email: "jammeh.kawsu@gmail.com",
      "E-Mail 2": "kjammehsopee@yahoo.com",
      lastName: "Jammeh",
      firstName: "Kawsu",
      country: "gm",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP PA-FP",
      prefix: "Mr.",
      organizationName: "Department of Parks & Wildlife Management",
     phone: "+220 310 2346, +220 277 9223",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6941",
      email: "peterjdery@yahoo.com",
      lastName: "Dery",
      firstName: "Peter J.",
      country: "gh",
      categoryList: "CBD-FP1 CHM-FP RM-FP",
      prefix: "Mr.",
      position: "Director of Environment",
      organizationName: "Ministry of Environment, Science, Technology and Innovation",
     phone: "+233 24 364 67 49",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6736",
      email: "melisa.ojeda@conap.gob.gt",
      "E-Mail 2": "megadiversidad@gmail.com",
      "E-Mail 3": "chmguatemala@gmail.com",
      lastName: "Ojeda Cabrera",
      firstName: "Leslie Melisa",
      country: "gt",
      categoryList: "CHM-FP ABSCH-PA BCH-FP",
      prefix: "Lic.",
      position: "Asesora",
      department: "Dirección de Valoración y Conservación de la Diversidad Biológica",
      organizationName: "Consejo Nacional de Áreas Protegidas (CONAP)",
     phone: "+502 1547 ext 1610, 502 2422 6700 ext 1610, 1611",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "2658",
      email: "doumbouyasaidou@yahoo.fr",
      "E-Mail 2": "doumbsaidou@gmail.com",
      lastName: "Doumbouya",
      firstName: "Saïdou",
      country: "gn",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Biologiste de formation",
      department: "Chef de Division Observation Aquatique et Atmosphérique en service au \r\nCentre d'Observation de Surveillance et d'Informations Environnementales (COSIE)",
      organizationName: "Ministère de l'Environnement, des Eaux et Forêts (MEEF)",
     phone: "+244 628 29 96 54",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6057",
      email: "arsaid.ibap@gmail.com",
      "E-Mail 2": "abilio.s.rachid@undp.org",
      lastName: "Said",
      firstName: "Abilio Rachid",
      country: "gw",
      categoryList: "CHM-FP",
      prefix: "Dr.",
      position: "Coordinator",
      department: "UNDP/GEF/IBAP Support Project \"Consolidation of Protected Area System in Guinea-Bissau's Forest Belt\"",
      organizationName: "Instituto da Biodiversidade e Áreas Protegidas (IBAP)",
     phone: "+245 677 0902 +245 576 8229",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7633",
      email: "srazack@epaguyana.org",
      lastName: "Razack",
      firstName: "Sharifah",
      country: "gy",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP ABS-FP ABSCH-PA CPB-FP1 BCH-FP",
      prefix: "Ms.",
      position: "Executive Director (ag)",
      organizationName: "Environmental Protection Agency (EPA)",
     phone: "+592 225 2062",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6962",
      email: "sotorene1959@yahoo.es",
      "E-Mail 2": "cooperacionserna@gmail.com",
      lastName: "Soto Rivera",
      firstName: "Rene Alfredo",
      country: "hn",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP PA-FP",
      prefix: "Mr.",
      position: "Director (Technical Focal Point)",
      department: "Dirección General de Biodiversidad",
      organizationName: "Secretaría de Recursos Naturales y Ambiente",
     phone: "+504 2239 8161",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "5825",
      email: "ditta.greguss@am.gov.hu",
      lastName: "Greguss",
      firstName: "Ditta",
      country: "hu",
      categoryList: "CBD-FP2 CHM-FP",
      prefix: "Ms.",
      position: "Biodiversity Advisor",
      department: "Biodiversity and Gene Conservation Department",
      organizationName: "Ministry of Agriculture",
     phone: "+36 1 795 3502",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3544",
      email: "s.kerketta66@gov.in",
      lastName: "Kerketta",
      firstName: "S.",
      country: "in",
      categoryList: "CBD-FP1 CHM-FP CBD-NR SBSTTA-FP ABS-FP ABSCH-IAC GTI-FP RM-FP GSPC-FP",
      prefix: "Dr.",
      position: "Advisor to the Government of India",
      organizationName: "Ministry of Environment, Forest and Climate Change",
     phone: "+91 11 24695249",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7344",
      email: "s_soufizadeh@sbu.ac.ir",
      lastName: "Soufizadeh",
      firstName: "Saeid",
      country: "ir",
      categoryList: "CHM-FP",
      prefix: "Dr.",
      position: "Advisor to the Primary National Focal Point and Assistant Professor in Agricultural Systems Modeling and Simulation",
      department: "Department of Agroecology, Environmental Sciences Research Institute",
      organizationName: "Shahid Beheshti University",
     phone: "+98 21 2243 1971",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6384",
      email: "alan.moore@chg.gov.ie",
      "E-Mail 2": "biodiversitypolicy@chg.gov.ie",
      lastName: "Moore",
      firstName: "Alan",
      country: "ie",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP ABS-FP PA-FP",
      prefix: "Mr.",
      position: "Assistant Principal Officer",
      department: "Biodiversity Policy",
      organizationName: "Department of Culture, Heritage and the Gaeltacht",
     phone: "+353 1 888 3206",
      organizationUrl: "https://www.chg.gov.ie/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "2800",
      email: "Ciaran.O'Keeffe@chg.gov.ie",
      "E-Mail 2": "biodiversitypolicy@chg.gov.ie",
      "E-Mail 3": "ciaran.okeeffe@ahg.gov.ie",
      lastName: "O'Keeffe",
      firstName: "Ciaran",
      country: "ie",
      categoryList: "CBD-FP1 CHM-FP CHM-NET PA-FP",
      prefix: "Dr.",
      position: "Head of Science and Bidoversity",
      department: "National Parks and Wildlife Service",
      organizationName: "Department of Culture, Heritage and the Gaeltacht",
     phone: "+353 1 888 3295",
      organizationUrl: "https://www.chg.gov.ie/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6059",
      email: "simon@npa.org.il",
      "E-Mail 2": "Tamarr@sviva.gov.il",
      "E-Mail 3": "anatrak@sviva.gov.il",
      lastName: "Nemtzov",
      firstName: "Simon",
      country: "il",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP ABS-FP PA-FP",
      prefix: "Dr.",
      position: "Head of International Relations",
      organizationName: "Israel Nature and Parks Authority",
     phone: "+972 58 5063118",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1169",
      email: "ayeletr@sviva.gov.il",
      "E-Mail 2": "lerond@sviva.gov.il",
      "E-Mail 4": "hilaco@sviva.gov.il",
      lastName: "Rosen",
      firstName: "Ayelet",
      country: "il",
      categoryList: "CBD-FP1 CHM-FP RM-FP",
      prefix: "Ms.",
      position: "Head",
      department: "Division of International Relations",
      organizationName: "Ministry of Environmental Protection",
     phone: "+972 2 65 53 745",
      organizationUrl: "www.sviva.gov.il",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5404",
      email: "dupre.eugenio@minambiente.it",
      lastName: "Duprè",
      firstName: "Eugenio",
      country: "it",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Officer",
      department: "Directorate General for Natural Heritage",
      organizationName: "Ministry for Ecological Transition",
     phone: "+39 06 5722 8200",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "2375",
      email: "chm@nhmj-ioj.org.jm",
      "E-Mail 2": "sdavis@nhmj-ioj.org.jm",
      "E-Mail 3": "suzmdavis@yahoo.com",
      lastName: "Davis",
      firstName: "Suzanne",
      country: "jm",
      categoryList: "CHM-FP CHM-IAC BCH-FP",
      prefix: "Dr.",
      position: "Senior Research Officer - Clearing House Mechanism",
      department: "Natural History Museum of Jamaica",
      organizationName: "Institute of Jamaica",
     phone: "+876 922 0620 6",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7490",
      email: "biodic_webmaster@env.go.jp",
      lastName: "Neagari",
      firstName: "Yasuko",
      country: "jp",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Survey Specialist",
      department: "Biodiversity Center of Japan, Nature Conservation Bureau",
      organizationName: "Ministry of the Environment",
     phone: "+81 555 72 6033",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5408",
      email: "hiroaki_tomoi@env.go.jp",
      lastName: "Tomoi",
      firstName: "Hiroaki",
      country: "jp",
      categoryList: "CHM-FP GTI-FP RM-FP",
      prefix: "Mr.",
      position: "Section Chief",
      department: "Biodiversity Strategy Office, Nature Conservation Bureau",
      organizationName: "Ministry of the Environment",
     phone: "+81 3 5521 8275",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6877",
      email: "elemesov.m@minagri.gov.kz",
      lastName: "Elemesov",
      firstName: "Maksat",
      country: "kz",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Head of Forestry and Protected Areas Unit",
      department: "Committee of Forestry and Wildlife",
      organizationName: "Ministry of Agriculture",
     phone: "+7 7172 74 38 98",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "6373",
      email: "dgnema@nema.go.ke",
      "E-Mail 2": "boru_mamo@yahoo.com",
      lastName: "Boru Mamo",
      firstName: "Mamo",
      country: "ke",
      categoryList: "CHM-FP ABS-CNA",
      prefix: "Mr.",
      position: "Acting Director General",
      organizationName: "National Environment Management Authority (NEMA)",
     phone: "+254 020 2103696",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7022",
      email: "secretary@melad.gov.ki",
      "E-Mail 2": "ds@melad.gov.ki",
      lastName: "Aukitino",
      firstName: "Taare",
      country: "ki",
      categoryList: "CBD-FP1 CHM-FP CHM-NET ABS-FP CPB-FP1 CPB-A17-FP",
      prefix: "Mrs.",
      position: "Secretary",
      organizationName: "Ministry of Environment, Lands and Agricultural Development (MELAD)",
     phone: "+686 28211",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6879",
      email: "decd@melad.gov.ki",
      "E-Mail 2": "secretary@melad.gov.ki",
      "E-Mail 3": "nteariki@gmail.com",
      lastName: "Teariki-Ruatu",
      firstName: "Nenenteiti",
      country: "ki",
      categoryList: "CBD-FP1 CHM-FP CHM-NET BCH-FP PA-FP",
      prefix: "Mrs.",
      position: "Director",
      department: "Environment and Conservation Division (ECD)",
      organizationName: "Ministry of Environment, Lands and Agricultural Development (MELAD)",
     phone: "+686 75028425, 75228211",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6837",
      email: "l.alawadhi@epa.org.kw",
      "E-Mail 2": "geology69@yahoo.com",
      lastName: "Alwadhi",
      firstName: "Leina",
      country: "kw",
      categoryList: "CBD-FP1 COP-BM CHM-FP SBSTTA-FP TKBD-FP PA-FP GTI-FP RM-FP GSPC-FP",
      prefix: "Ms.",
      department: "Department of Biodiversity Conservation",
      organizationName: "Environment Public Authority",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "7477",
      email: "bemamo@mail.ru",
      "E-Mail 2": "envforest@elcat.kg",
      "E-Mail 3": "min-eco@elcat.kg",
      lastName: "Omurova",
      firstName: "Bermet",
      country: "kg",
      categoryList: "CHM-FP ABS-FP BCH-FP",
      prefix: "Ms.",
      position: "Deputy Head",
      department: "International Cooperation Department",
      organizationName: "State Agency on Environment Protection and Forestry (SAEPF)",
     phone: "+996 312 54 60 73",
      organizationUrl: "http://www.ecology.gov.kg/",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "6634",
      email: "inthavymrc@gmail.com",
      lastName: "Akkharath",
      firstName: "Inthavy",
      country: "la",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR",
      prefix: "Dr.",
      position: "Assistant to Minister",
      department: "Cabinet Office",
      organizationName: "Ministry of Natural Resources and Environment (MoNRE)",
     phone: "+856 21 261 196",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "5011",
      email: "chaynoym@yahoo.com",
      lastName: "Sisomphane",
      firstName: "Chaynoy",
      country: "la",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Head, Agriculture and Wild Animal Sector",
      department: "Department of Forestry (DOF)",
      organizationName: "Ministry of Agriculture and Forestry (MAF)",
     phone: "+856 21 216921",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "5397",
      email: "andris.soms@daba.gov.lv",
      lastName: "Soms",
      firstName: "Andris",
      country: "lv",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Senior Specialist (Projection of Information Systems)",
      department: "Department of Nature (Protected Areas)",
      organizationName: "Nature Conservation Agency",
     phone: "+371 67509768, +371 64071408",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1345",
      email: "l.samaha@moe.gov.lb",
      lastName: "Samaha",
      firstName: "Lara",
      country: "lb",
      categoryList: "CBD-FP1 CHM-FP CHM-NET ABS-FP CPB-FP1 BCH-FP",
      prefix: "Ms.",
      position: "Head",
      department: "Department of Conservation of Natural Wealth",
      organizationName: "Ministry of Environment",
     phone: "+961 1 976 555 ext 417",
      organizationUrl: "www.moe.gov.lb",
      unLang: "AR-FR-EN",
      mailOutLang: "AF"
  },
  {
      id:  "2404",
      email: "qhoohlo@hotmail.com",
      lastName: "Hoohlo",
      firstName: "Qongqong",
      country: "ls",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Ms.",
      position: "Environment Officer - Data",
      department: "National Environment Secretariat",
      organizationName: "Ministry of Tourism, Environment and Culture",
     phone: "+266 58 849 056",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "2424",
      email: "jcammue@epa.gov.lr",
      lastName: "Cammue",
      firstName: "J.S. Datuama",
      country: "lr",
      categoryList: "CBD-FP1 CHM-FP CPB-A17-FP BCH-FP",
      prefix: "Mr.",
      organizationName: "Environmental Protection Agency (EPA)",
     phone: "+231 885 128732",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3677",
      email: "a.alisauskiene@am.lt",
      lastName: "Alisauskiene",
      firstName: "Sigute",
      country: "lt",
      categoryList: "CHM-FP CHM-NET GSPC-FP",
      prefix: "Mrs.",
      position: "Chief Officer of Biodiversity Division",
      department: "Nature Protection Department",
      organizationName: "Ministry of Environment",
     phone: "+370 52 663 551",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1102",
      email: "Claude.Origer@mev.etat.lu",
      "E-Mail 2": "eric.schauls@mev.etat.lu",
      lastName: "Origer",
      firstName: "Claude",
      country: "lu",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR PA-FP",
      prefix: "Mr.",
      position: "Conseiller de Direction 1ère classe",
      department: "Département de l'Environnement",
      organizationName: "Ministère de l'Environnement, du Climat et du Développement durable",
     phone: "+352 247 86826",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7343",
      email: "laurent@pnae.mg",
      "E-Mail 2": "laurent0083@gmail.com",
      lastName: "Ampilahy",
      firstName: "Laurent",
      country: "mg",
      categoryList: "CHM-FP",
      prefix: "M.",
      position: "Directeur General",
      department: "Office National pour l'Environnement",
      organizationName: "Ministère de l’Environnement et du Développement Durable",
     phone: "+261 34 02 792 84",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7103",
      email: "benyassin@gmail.com",
      lastName: "Yassin",
      firstName: "Benon Bibbu",
      country: "mw",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Deputy Director",
      organizationName: "Environmental Affairs Department",
     phone: "+265 1 771 111",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5157",
      email: "lilian@frim.gov.my",
      lastName: "Swee Lian",
      firstName: "Lillian Chua",
      country: "my",
      categoryList: "CHM-FP GTI-CM",
      prefix: "Dr.",
      position: "Senior Research Officer",
      department: "Forest Biodiversity Division",
      organizationName: "Forest Research Institute of Malaysia (FRIM)",
     phone: "+603 6279 7218",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5849",
      email: "ilham.mohamed@environment.gov.mv",
      lastName: "Mohamed",
      firstName: "Ilham Atho",
      country: "mv",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP CPB-FP1 CPB-A17-FP",
      prefix: "Ms.",
      position: "Assistant Director",
      department: "Environment Programme",
      organizationName: "Ministry of Environment",
     phone: "+960 301 8357",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7368",
      email: "amidougoita@gmail.com",
      lastName: "Goïta",
      firstName: "Amidou",
      country: "ml",
      categoryList: "CHM-FP",
      prefix: "M.",
      position: "Chef, Section Données sur Environment",
      department: "Département information Environnementale (DIE)",
      organizationName: "Agence de l’Environnementale et du Développement Durable (AEDD)",
     phone: "+ 223 20 23 10 74",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6888",
      email: "bch.malta@era.org.mt",
      "E-Mail 2": "marie-therese.gambin@era.org.mt",
      "E-Mail 3": "chm.malta@era.org.mt",
      lastName: "Gambin",
      firstName: "Marie Therese",
      country: "mt",
      categoryList: "CHM-FP CPB-FP1 CPB-A17-FP BCH-FP TKBD-FP PA-FP",
      prefix: "Ms.",
      position: "Unit Manager Thematic",
      department: "Biodiversity and Water Unit",
      organizationName: "Environment and Resources Authority",
     phone: "+356 2292 3659",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3835",
      email: "bamouss14@gmail.com",
      lastName: "Ba",
      firstName: "Moussa",
      country: "mr",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP ABSCH-PA CPB-FP1 CPB-A17-FP BCH-FP PA-FP GTI-FP RM-FP GSPC-FP",
      prefix: "M.",
      position: "Conseiller Juridique",
      organizationName: "Ministère de l’Environnement et du Développement Durable",
     phone: "+222 46 01 31 31, +222 27 31 09 52",
      unLang: "AR-FR-EN",
      mailOutLang: "AF"
  },
  {
      id:  "1148",
      email: "npcsagr@intnet.mu",
      "E-Mail 2": "vbachraz@govmu.org",
      lastName: "Bachraz",
      firstName: "Vishnuduth",
      country: "mu",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Acting Director",
      organizationName: "National Parks and Conservation Service",
     phone: "+230 4642 992, +230 466 2116",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3176",
      email: "christine.external@mail.gov.nu",
      "E-Mail 2": "external@mail.gov.nu",
      lastName: "Ioane",
      firstName: "Christine",
      country: "nu",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP",
      prefix: "Ms.",
      position: "Director",
      department: "Cabinet and Parliamentary Services",
      organizationName: "Office for External Affairs",
     phone: "+683 4200",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7027",
      email: "cgalindo@conabio.gob.mx",
      lastName: "Galindo Leal",
      firstName: "Carlos",
      country: "mx",
      categoryList: "CHM-FP CHM-IAC",
      prefix: "Sr.",
      position: "Director General de Comunicación de la Ciencia",
      organizationName: "Comisión Nacional para el Conocimiento y Uso de Biodiversidad (CONABIO)",
     phone: "+52 55 50044973",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "6740",
      email: "cevanklaveren@gouv.mc",
      lastName: "van Klaveren-Impagliazzo",
      firstName: "Céline",
      country: "mc",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR BCH-FP",
      prefix: "Madame",
      position: "Secrétaire des Relations Extérieures",
      department: "Direction des Affaires Internationales",
      organizationName: "Département des Relations Extérieures et de la Coopération",
     phone: "+377 98 98 44 70",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6903",
      email: "bayasgalana@gmail.com",
      lastName: "Bayasgalan",
      firstName: "Amgalan",
      country: "mn",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Biodiversity Officer",
      department: "Department of Environment and Natural Resource Authority",
      organizationName: "Ministry of Environment and Tourism",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "2046",
      email: "madbouhi@environnement.gov.ma",
      "E-Mail 2": "mostamad@gmail.com",
      "E-Mail 3": "mostamad@yahoo.fr",
      lastName: "Madbouhi",
      firstName: "Mostafa",
      country: "ma",
      categoryList: "CBD-FP1 CHM-FP CHM-IAC ABS-FP ABSCH-PA CPB-FP1 BCH-FP",
      prefix: "M.",
      position: "Chef de la Division de la Diversité Biologique",
      department: "Direction du Changement Climatique, de la Diversité Biologique et de l'Économie Verte",
      organizationName: "Ministère de l'Energie, des Mines et de l'Environnement",
     phone: "+212 5 37 57 06 02",
      unLang: "AR-FR-EN",
      mailOutLang: "AF"
  },
  {
      id:  "112",
      email: "melinhapaula@yahoo.com.br",
      "E-Mail 2": "melinhapaula@gmail.com",
      lastName: "Tomás Francisco",
      firstName: "Ana Paula",
      country: "mz",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR",
      prefix: "Ms.",
      position: "Environmental Technician",
      department: "National Directorate of Environment",
      organizationName: "Ministry of Land and Environment",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6947",
      email: "nwcdfdmof@gmail.com",
      lastName: "Htun",
      firstName: "Naing Zaw",
      country: "mm",
      categoryList: "CHM-FP SBSTTA-FP RM-FP",
      prefix: "Dr.",
      position: "Director, Nature and Wildlife Conservation Division",
      department: "Forest Department",
      organizationName: "Ministry of Natural Resources and Environmental Conservation",
     phone: "+95 67 340 5002",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5034",
      email: "timoteus.mufeti@met.gov.na",
      "E-Mail 2": "tmufeti@afromach.com",
      lastName: "Mufeti",
      firstName: "Timoteus",
      country: "na",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP",
      prefix: "Mr.",
      position: "Environmental Commissioner and Head",
      department: "Directorate of Environmental Affairs and Forestry",
      organizationName: "Ministry of Environment, Forestry and Tourism",
     phone: "+264 61 284 2751",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "4881",
      email: "secretarycienauru@gmail.com",
      lastName: "Jeremiah",
      firstName: "Berilyn",
      country: "nr",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR CPB-FP1 BCH-FP",
      prefix: "Mrs.",
      position: "Secretary for Commerce, Industry and Environment",
      organizationName: "Department of Commerce, Industry and Environment",
     phone: "+674 557 3133 ext 293",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7598",
      email: "shiva1967@live.com",
      "E-Mail 2": "shivakwagle@gmail.com",
      lastName: "Wagle",
      firstName: "Shiva Kumar",
      country: "np",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP CPB-FP1 BCH-FP PA-FP RM-FP",
      prefix: "Mr.",
      position: "Joint Secretary",
      department: "Chief, Environment and Biodiversity Division",
      organizationName: "Ministry of Forests and Environment",
     phone: "+9779841738487",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3259",
      email: "r.j.j.hendriks@mineleni.nl",
      lastName: "Hendriks",
      firstName: "Rob J.J.",
      country: "nl",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      department: "Directorate for AgroKnowledge",
      organizationName: "Ministry of Economic Affairs and Climate Policy",
     phone: "+31 648132449",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7313",
      email: "mhunt@doc.govt.nz",
      lastName: "Hunt",
      firstName: "Maya",
      country: "nz",
      categoryList: "CHM-FP PA-FP GSPC-FP",
      prefix: "Ms.",
      position: "Senior International Advisor",
      department: "Department of Conservation - Te Papa Atawhai",
     phone: "+64 27 5755 490",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6932",
      email: "issaka.mamansani@yahoo.fr",
      lastName: "Sani",
      firstName: "Issaka Maman",
      country: "ne",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      organizationName: "Conseil National de l'Environnement pour un Développement Durable (CNEDD)",
     phone: "+227 96 68 01 26",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6787",
      email: "sikeadeegbuwalo@gmail.com",
      lastName: "Egbuwalo",
      firstName: "Sikeade Oluwakemi",
      country: "ng",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP",
      prefix: "Mrs.",
      position: "Forest Officer I",
      department: "Federal Department of Forestry",
      organizationName: "Federal Ministry of Environment",
     phone: "+234 703 2743344",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5909",
      email: "andreas.benjamin.schei@miljodir.no",
      lastName: "Schei",
      firstName: "Andreas Benjamin",
      country: "no",
      categoryList: "CHM-FP SBSTTA-FP GTI-FP",
      prefix: "Mr.",
      position: "Senior Adviser",
      organizationName: "Norwegian Environment Agency",
     phone: "+47 988 59 994, +47 73 58 05 00",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5778",
      email: "icd@meca.gov.om",
      lastName: "Al-Sinaidi",
      firstName: "Mohamed Rashid",
      country: "om",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP CPB-FP1 GTI-FP GSPC-FP",
      prefix: "Mr.",
      position: "Managing Director",
      department: "International Co-operation Department",
      organizationName: "Ministry of Environment and Climate Affairs",
     phone: "+968 24404817",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "6413",
      email: "mnretpalau@gmail.com",
      country: "pw",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP PA-FP GTI-FP",
      position: "Minister",
      organizationName: "Ministry of Agriculture, Fisheries, and the Environment",
     phone: "+680 767 5435, 3125",
      organizationUrl: "http://palaugov.pw/natural-resources/",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6412",
      email: "gsisior07@gmail.com",
      lastName: "Sisior",
      firstName: "Gwendalyn K.",
      country: "pw",
      categoryList: "CBD-FP2 SBSTTA-BM CHM-FP SBSTTA-FP PA-FP",
      prefix: "Ms.",
      position: "EPCU Coordinator",
      department: "Office of the Minister",
      organizationName: "Ministry of Agriculture, Fisheries, and the Environment",
     phone: "+ 680 767 5435, 3125",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3532",
      email: "dluque@miambiente.gob.pa",
      "E-Mail 2": "dluque@yahoo.com",
      lastName: "Luque",
      firstName: "Darío",
      country: "pa",
      categoryList: "CHM-FP CHM-NET ABSCH-PA GSPC-FP",
      prefix: "Sr.",
      position: "Técnico de Biodiversidad y Vida Silvestre",
      department: "Departamento de Biodiversidad y Vida Silvestre",
      organizationName: "Ministerio de Ambiente",
     phone: "+507 500 0855 ext 6877 +507 500 0822",
      organizationUrl: "www.anam.gob.pa",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "6074",
      email: "dariomandel@gmail.com",
      country: "py",
      categoryList: "CHM-FP CHM-NET SBSTTA-FP",
      organizationName: "Ministerio del Ambiente y Desarrollo Sostenible",
     phone: "+595 21 615 805, 615 812, 615 814",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "5977",
      email: "rsolis@minam.gob.pe",
      lastName: "Solis Ortiz",
      firstName: "Roxana",
      country: "pe",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Especialista en Monitoreo de la Biodiversidad",
      organizationName: "Ministerio del Ambiente",
     phone: "+51 1 611 6000 ext 1340",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "7361",
      email: "director@bmb.gov.ph",
      "E-Mail 2": "bmb@bmb.gov.ph",
      lastName: "Calderon",
      firstName: "Ricardo L.",
      country: "ph",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP PA-FP",
      prefix: "Mr.",
      position: "Director",
      department: "Biodiversity Management Bureau (BMB)",
      organizationName: "Department of Environment and Natural Resources (DENR)",
     phone: "+632 924 6031 ext 203 and 204",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3693",
      email: "malgorzata.rozynska@mos.gov.pl",
      lastName: "Jankowska-Rozynska",
      firstName: "Malgorzata",
      country: "pl",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Ms.",
      position: "Specialist",
      department: "Directorate General for Environmental Protection",
      organizationName: "Ministry of Climate and Environment",
     phone: "+48 22 57 92 667",
      organizationUrl: "http://biodiv.mos.gov.pl/biodiv",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7538",
      email: "NMAL-Mansoori@mme.gov.qa",
      lastName: "Al-Mansoori",
      firstName: "Nasser M.",
      country: "qa",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP CPB-FP1 CPB-A17-FP BCH-FP",
      prefix: "Mr.",
      position: "Biological Researcher",
      department: "Department of Environmental Protection and Wildlife",
      organizationName: "Ministry of Municipality and Environment",
     phone: "+974 44263773",
      organizationUrl: "http://www.mme.gov.qa/cui/index.dox",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "6422",
      email: "cbdrok@korea.kr",
      lastName: "Chung",
      firstName: "Younhwan",
      country: "kr",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP TKBD-FP PA-FP RM-FP",
      prefix: "Mr.",
      position: "Deputy Director",
      department: "Biodiversity Division",
      organizationName: "Ministry of Environment",
     phone: "+82 44 201 7243",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7364",
      email: "leejaeho@korea.kr",
      lastName: "Lee",
      firstName: "Jaeho",
      country: "kr",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Senior Researcher",
      department: "Genetic Resources Information Center",
      organizationName: "National Institute of Biological Resources",
     phone: "+82 32 590 7062",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7484",
      email: "dumitru.gorelco@madrm.gov.md",
      "E-Mail 2": "gorelcomailbox@gmail.com",
      lastName: "Gorelco",
      firstName: "Dumitru",
      country: "md",
      categoryList: "CBD-FP1 CHM-FP PA-FP",
      prefix: "Mr.",
      position: "Head",
      department: "Biodiversity Policies Department",
      organizationName: "Ministry of Agriculture, Regional Development and Environment",
     phone: "+373 22 204 511, +373 79 813 197",
      organizationUrl: "http://www.madrm.gov.md",
      unLang: "RU-EN",
      mailOutLang: "E"
  },
  {
      id:  "3173",
      email: "Sauni.Tongatule@mail.gov.nu",
      lastName: "Tongatule",
      firstName: "Sauni",
      country: "nu",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP ABS-FP CPB-FP1 BCH-FP PA-FP RM-FP",
      prefix: "Mr.",
      position: "Director",
      department: "Department of Environment",
      organizationName: "Ministry of Natural Resources",
     phone: "+683 4021",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7606",
      email: "breda.ogorelec@gov.si",
      lastName: "Ogorelec",
      firstName: "Breda",
      country: "si",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Secretary",
      department: "Sector for Nature Conservation",
      organizationName: "Ministry for the Environment and Spatial Planning",
     phone: "+386 1 478 7430",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3526",
      email: "horokoujoe@gmail.com",
      "E-Mail 2": "JHorokou@mecdm.gov.sb",
      lastName: "Horokou",
      firstName: "Joe",
      country: "sb",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR",
      prefix: "Mr.",
      position: "Director",
      department: "Environment and Conservation Division",
      organizationName: "Ministry of Environment, Climate Change, Disaster Management and Meteorology",
     phone: "+677 23 031 +677 24 215, +677 88 481",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6912",
      email: "dg@environment.gov.so",
      lastName: "Ahmed",
      firstName: "Ahmed Yusuf",
      country: "so",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP PA-FP GTI-FP GSPC-FP",
      prefix: "Mr.",
      position: "Director General",
      department: "Directorate of Environment and Climate Change",
      organizationName: "Office of the Prime Minister",
     phone: "+252617886632",
      unLang: "AR-EN",
      mailOutLang: "E"
  },
  {
      id:  "4868",
      email: "MQwathekana@environment.gov.za",
      "E-Mail 2": "greenpeople@webmail.co.za",
      lastName: "Qwathekana",
      firstName: "Malta",
      country: "za",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP GTI-FP GSPC-FP",
      prefix: "Ms.",
      position: "Senior Policy Adviser; CBD Technical (Principal) Focal Point",
      department: "International Biodiversity and Heritage Cooperation",
      organizationName: "Department of Environment, Forestry and Fisheries",
     phone: "+27 12 310 3067",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6681",
      email: "ladolodemen@yahoo.com",
      lastName: "Demetry",
      firstName: "Paul L.",
      country: "ss",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP RM-FP",
      prefix: "Mr.",
      position: "Deputy Director for Biodiversity",
      department: "Directorate of Wetlands and Biodiversity",
      organizationName: "Ministry of Environment and Forestry",
     phone: "+211 956 600801"
  },
  {
      id:  "7280",
      email: "tiba_lwanga@yahoo.com",
      lastName: "Tiba Charles",
      firstName: "Lwanga",
      country: "ss",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Directorate of Wetlands and Biodiversity",
      organizationName: "Ministry of Environment and Forestry"
  },
  {
      id:  "7497",
      email: "sgracia@miteco.es",
      lastName: "Gracia Campillo",
      firstName: "Santiago",
      country: "es",
      categoryList: "CHM-FP SBSTTA-FP",
      prefix: "Mr.",
      position: "Jefe de Servicio de Especies Amenazadas",
      department: "Dirección General de Biodiversidad, Bosques y Desertificación",
      organizationName: "Ministerio para la Transición Ecológica y el Reto Demográfico",
     phone: "+34 91 597 57 12",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "5941",
      email: "pathma66a@gmail.com",
      "E-Mail 2": "biodiversitysl@gmail.com",
      lastName: "Abeykoon",
      firstName: "R.H.M.P.",
      country: "lk",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP PA-FP GSPC-FP",
      prefix: "Mrs.",
      position: "Director (Operational Focal Point)",
      department: "Biodiversity Secretariat",
      organizationName: "Ministry of Environment",
     phone: "+94 11 2034202",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7614",
      email: "sec@env.gov.lk",
      lastName: "Jasinghe",
      firstName: "Anil",
      country: "lk",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP ABS-FP CPB-FP1 CPB-A17-FP BCH-FP MAR-FP GSPC-FP",
      prefix: "Dr.",
      position: "Secretary",
      organizationName: "Ministry of Environment",
     phone: "+94 11 2034121, +94 11 2034122",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6563",
      email: "elkhitmamohammed@gmail.com",
      lastName: "Mohammed",
      firstName: "El Khitma El Awad",
      country: "sd",
      categoryList: "CHM-FP SBSTTA-FP NP-CC ABSCH-PA",
      prefix: "Dr.",
      position: "Senior Researcher",
      department: "Biodiversity",
      organizationName: "Higher Council for Environment and Natural Resources (HCENR)",
     phone: "+249 183 784279, +249 9 12814558",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "7261",
      lastName: "Jarjanazi",
      firstName: "Mais",
      country: "sy",
      categoryList: "CHM-FP",
      prefix: "Eng.",
      department: "Environmental Research Directorate",
      organizationName: "Ministry of Local Administration and Environment",
     phone: "+00963 11 2318682",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "7631",
      email: "krissana.cherry@gmail.com",
      "E-Mail 2": "krissanas@onep.go.th",
      lastName: "Sukniwatchai",
      firstName: "Krissana",
      country: "th",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Environmentalist, Professional Level",
      department: "Biological Diversity Management Division",
      organizationName: "Office of Natural Resources and Environmental Policy and Planning",
     phone: "+662 265 6565",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7319",
      email: "torpattarin@gmail.com",
      "E-Mail 2": "pattarin@onep.go.th",
      lastName: "Tongsima",
      firstName: "Pattarin",
      country: "th",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Environmentalist, Senior Professional Level",
      department: "Biological Diversity Management Division",
      organizationName: "Office of Natural Resources and Environmental Policy and Planning",
     phone: "+662 265 6565",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7300",
      email: "danny.heptinstall@jncc.gov.uk",
      lastName: "Heptinstall",
      firstName: "Danny",
      country: "gb",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Senior International Biodiversity Adviser",
      organizationName: "UK Joint Nature Conservation Committee (JNCC)",
     phone: "+44 0 1733 866 949",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5783",
      email: "derosabm@state.gov",
      lastName: "De Rosa-Joynt",
      firstName: "Barbara",
      country: "us",
      categoryList: "CBD-FP1 CHM-FP SBSTTA-FP",
      prefix: "Ms.",
      position: "Division Chief for Biodiversity, Office of Conservation and Water",
      department: "Bureau of Oceans and International Environmental and Scientific Affairs",
      organizationName: "Department of State",
     phone: "+1 202 647 4511",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7078",
      email: "ana.mello@mvotma.gub.uy",
      lastName: "Mello",
      firstName: "Ana Laura",
      country: "uy",
      categoryList: "CHM-FP SBSTTA-FP CPB-A17-FP GTI-FP MAR-FP",
      prefix: "Lic. MSc.",
      position: "Directora de la División de Biodiversidad",
      organizationName: "Ministerio de Vivienda, Ordenamiento Territorial y Medio Ambiente (MVOTMA)",
     phone: "+598 2917 0710 ext 4457",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "7426",
      email: "gulya8212@bk.ru",
      lastName: "Shagiakhmetova",
      firstName: "G",
      country: "uz",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Head of Scientific, Environmental Educaton and Recreational Activities Division",
      department: "State Committee for Ecology and Environmental Protection",
     phone: "+998 71 207 2424 ext 1010",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "4999",
      email: "ybasil@vanuatu.gov.vu",
      "E-Mail 2": "taritrinison@gmail.com",
      country: "vu",
      categoryList: "CHM-FP CHM-NET BCH-FP",
      department: "Department of Environmental Protection and Conservation",
      organizationName: "Ministry of Climate Change Adaptation, Meteorology and Geo-Hazards, Environment, Energy and Disaster Management",
     phone: "+678 25302, 22227",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "4309",
      email: "carlizdiaz@gmail.com",
      "E-Mail 2": "diversidadbiologicaven.dg@gmail.com",
      lastName: "Díaz Martinez",
      firstName: "Carliz Elena",
      country: "ve",
      categoryList: "CHM-FP ABS-FP CPB-FP1 CPB-A17-FP BCH-FP TKBD-FP",
      prefix: "Ms.",
      position: "Agrónomo",
      department: "Dirección General de Diversidad Biológica",
      organizationName: "Ministerio del Poder Popular para el Ecosocialismo (MINEC)",
     phone: "+58 212 408 4730, 4785",
      unLang: "ES-EN",
      mailOutLang: "S"
  },
  {
      id:  "5418",
      email: "huyentrang1601@gmail.com",
      lastName: "Trang",
      firstName: "Tran Huyen",
      country: "vn",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Official",
      department: "Nature and Biodiversity Conservation Agency",
      organizationName: "Vietnam Environment Administration",
     phone: "+84 988741212",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7084",
      email: "ammar.aulaqi@gmail.com",
      "E-Mail 2": "info@epa-ye.org",
      lastName: "Al-Aulaqi",
      firstName: "Ammar",
      country: "ye",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP ABS-FP CPB-FP1 CPB-A17-FP BCH-FP PA-FP",
      prefix: "Mr.",
      position: "Chairman",
      organizationName: "Environment Protection Authority (EPA)",
      organizationUrl: "https://www.epa-ye.org/",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "3801",
      email: "nkula14@yahoo.com",
      lastName: "Mwanza",
      firstName: "Nkula",
      country: "zm",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Acting Data Manager",
      department: "Planning and Information Department",
      organizationName: "Ministry of Lands and Natural Resources",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1249",
      email: "ozone@gta.gov.zw",
      lastName: "Chipato",
      firstName: "C.",
      country: "zw",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Permanent Secretary for Mines, Environment and Tourism",
      organizationName: "Ministry of Environment, Climate, Tourism and Hospitality Industry",
     phone: "+263 4 757 881, 5",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "4164",
      email: "roxana.ionescu@mmediu.ro",
      lastName: "Ionescu",
      firstName: "Roxana",
      country: "ro",
      categoryList: "CHM-FP BCH-FP",
      prefix: "Ms.",
      position: "Senior Adviser",
      department: "Biodiversity Directorate",
      organizationName: "Ministry of Environment, Waters and Forests",
     phone: "+40 21 408 95 46, +40 72 001 07 01",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "5417",
      email: "nsanzimana@gmail.com",
      lastName: "Nsanzimana",
      firstName: "Djuma",
      country: "rw",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Environmental Education Officer",
      organizationName: "Rwanda Environment Management Authority (REMA)",
     phone: "+250 788 863 539",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6659",
      email: "jannel.gabriel@govt.lc",
      "E-Mail 2": "jgabriel.sded@gmail.com",
      "E-Mail 3": "jannelgabriel@gmail.com",
      "E-Mail 4": "levistmarie@gmail.com",
      lastName: "Gabriel",
      firstName: "Jannel",
      country: "lc",
      categoryList: "CHM-FP ABS-FP BCH-FP",
      prefix: "Ms.",
      position: "Sustainable Development and Environment Officer II",
      department: "Department of Sustainable Development",
      organizationName: "Ministry of Education, Innovation, Gender Relations and Sustainable Development",
     phone: "+1 758 468 5886, +1 758 724 7134",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7601",
      email: "anitamontoute.dsd@gmail.com",
      lastName: "Montoute",
      firstName: "Anita",
      country: "lc",
      categoryList: "CBD-FP1 CHM-FP ABS-FP CPB-FP1",
      prefix: "Mrs.",
      position: "Permanent Secretary",
      department: "Department of Sustainable Development",
      organizationName: "Ministry of Education, Innovation, Gender Relations and Sustainable Development",
     phone: "+1 758 468 5840, +1 758 717 1232",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5239",
      email: "sandro.casali@pa.sm",
      lastName: "Casali",
      firstName: "Sandro",
      country: "sm",
      categoryList: "CBD-FP1 CHM-FP BCH-FP",
      prefix: "Mr.",
      position: "Head",
      organizationName: "San Marino Naturalistic Center",
     phone: "+378 0549 883462, +378 0549 883460",
      organizationUrl: "http://www.interni.segreteria.sm/index.php?id=218",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "1195",
      email: "bureau_ozono@cstome.net",
      "E-Mail 2": "arceitacarv@hotmail.com",
      lastName: "De Ceita Carvalho",
      firstName: "Arlindo",
      country: "st",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Directeur National du Cabinet de l'Environnement",
      organizationName: "Ministry of Public Works, Infrastructures, Natural Resources and Environment",
     phone: "+239 225 271; 239 226 264; 239 4018",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "7281",
      email: "f.Shuraim@swa.gov.sa",
      "E-Mail 2": "sbstta_nfp@swa.gov.sa",
      lastName: "Shuraim",
      firstName: "Faisal",
      country: "sa",
      categoryList: "CHM-FP SBSTTA-FP",
      prefix: "Mr.",
      position: "Executive Secretary",
      department: "Secretariat of the National Committee for Biodiversity",
      organizationName: "National Center for Wildlife",
     phone: "+966 11 44 10 797",
      unLang: "AR-EN",
      mailOutLang: "A"
  },
  {
      id:  "1126",
      email: "ajaasy@yahoo.fr",
      lastName: "Aïssatou Sy",
      firstName: "Adja",
      country: "sn",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Ms.",
      organizationName: "Institut des Sciences de l'Environnement - Université de Dakar",
     phone: "+221 77 656 15 25",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "4296",
      email: "slavisa.popovic@sepa.gov.rs",
      lastName: "Popovic",
      firstName: "Slavisa",
      country: "rs",
      categoryList: "CHM-FP CHM-IAC",
      prefix: "Mr.",
      organizationName: "Environmental Protection Agency (SEPA)",
     phone: "+381 11 241 39 66",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6906",
      email: "j.prosper@env.gov.sc",
      lastName: "Prosper",
      firstName: "Justin",
      country: "sc",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Principal GIS Officer",
      organizationName: "Ministry of Environment, Energy and Climate Change",
     phone: "+248 2722301",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "1932",
      email: "bathkay@yahoo.co.uk",
      lastName: "Kamara",
      firstName: "Bartholomew",
      country: "sl",
      categoryList: "CHM-FP CHM-NET",
      prefix: "Mr.",
      position: "Project Coordinator",
      department: "Biodiversity Strategy and Action Plan",
      organizationName: "Ministry of Agriculture, Forestry & Food Security",
     phone: "+232 22 242095, 076607425",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "5464",
      email: "lim_li-feng@nparks.gov.sg",
      lastName: "Li-Feng",
      firstName: "Lim",
      country: "sg",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Deputy Director/Biodiversity Information and Policy",
      department: "National Biodiversity Centre",
      organizationName: "National Parks Board",
     phone: "+65 6465 1681",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7330",
      email: "Jeremy_YAP@nparks.gov.sg",
      lastName: "Yap Jun Sean",
      firstName: "Jeremy",
      country: "sg",
      categoryList: "CHM-FP PA-FP RM-FP MAR-FP GSPC-FP",
      prefix: "Mr.",
      position: "Manager/International Biodiversity Conservation",
      department: "International Biodiversity Conservation Division",
      organizationName: "National Parks Board",
     phone: "+65 6465 2985",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6385",
      email: "eva.viestova@enviro.gov.sk",
      "E-Mail 2": "biodiversity@enviro.gov.sk",
      lastName: "Viestová",
      firstName: "Eva",
      country: "sk",
      categoryList: "CBD-FP1 CHM-FP CHM-NET PA-FP GTI-FP",
      prefix: "Ms.",
      department: "Directorate for Nature Protection and Landscape Development",
      organizationName: "Ministry of Environment",
     phone: "+421 2 5956 2546",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "4260",
      email: "lai_luhat78@yahoo.com",
      lastName: "Mendes",
      firstName: "Manuel",
      country: "tl",
      categoryList: "CHM-FP PA-FP",
      prefix: "Mr.",
      position: "Director for the National Directorate for Protected Areas",
      organizationName: "Ministry of Agriculture and Fisheries",
     phone: "+670 727 5236",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7536",
      email: "eric.agbe@yahoo.fr",
      "E-Mail 2": "direfaune@yahoo.fr",
      lastName: "Agbessi",
      firstName: "K. Ganyo Eric",
      country: "tg",
      categoryList: "CHM-FP",
      prefix: "M.",
      position: "Biologist aménagiste forestier, spécialiste en SIG",
      department: "Direction des ressources forestières",
      organizationName: "Ministère de l'Environnement et des Ressources forestières",
     phone: "+228 22 21 86 43, 90 16 66 74",
      unLang: "FR-EN",
      mailOutLang: "F"
  },
  {
      id:  "6318",
      email: "joanne.deoraj@planning.gov.tt",
      "E-Mail 2": "ajsdeo@yahoo.com",
      "E-Mail 3": "kishan.kumarsingh@planning.gov.tt",
      lastName: "Deoraj",
      firstName: "Joanne",
      country: "tt",
      categoryList: "CBD-FP1 CHM-FP CHM-NET SBSTTA-FP PA-FP RM-FP",
      prefix: "Ms.",
      position: "Permanent Secretary",
      organizationName: "Ministry of Planning and Development",
     phone: "+1 868 612 3000 ext 2016, 1329",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6319",
      email: "kishan.kumarsingh@planning.gov.tt",
      lastName: "Kumarsingh",
      firstName: "Kishan",
      country: "tt",
      categoryList: "CBD-FP2 CHM-FP SBSTTA-FP PA-FP GTI-FP GSPC-FP",
      prefix: "Mr.",
      position: "Head (Alternative Contact Point)",
      department: "Multilateral Environmental Agreements Unit",
      organizationName: "Ministry of Planning and Development",
     phone: "+1 868 225 3381",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "6959",
      email: "Hatem_medd@yahoo.fr",
      "E-Mail 2": "Hatem.BenBelgacem@mineat.gov.tn",
      lastName: "Ben Belgacem",
      firstName: "Hatem",
      country: "tn",
      categoryList: "CHM-FP CPB-FP1 BCH-FP",
      prefix: "M.",
      position: "Ingénieur en Chef et Sous-Directeur des Etudes Economiques et Environnementales",
      department: "Direction Générale de l'Environnement et de la Qualité de la Vie (DGEQV)",
      organizationName: "Ministère des Affaires Locales et de l’Environnement (MALE)",
     phone: "+216 97456862",
      unLang: "AR-FR-EN",
      mailOutLang: "AF"
  },
  {
      id:  "7652",
      email: "serkan.camalan@tarimorman.gov.tr",
      lastName: "Çamalan",
      firstName: "Serkan",
      country: "tr",
      categoryList: "CHM-FP",
      prefix: "Mr.",
      position: "Forestry and Agriculture Specialist",
      organizationName: "Ministry of Agriculture and Forestry",
     phone: "+90 312 207 6274",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "7651",
      email: "fulya.yaycili@tarimorman.gov.tr",
      lastName: "Yaycili",
      firstName: "Fulya",
      country: "tr",
      categoryList: "CHM-FP",
      prefix: "Ms.",
      position: "Forestry and Agriculture Specialist",
      organizationName: "Ministry of Agriculture and Forestry",
     phone: "+90 312 207 5944",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "2805",
      email: "shirinkarryeva.sk@gmail.com",
      lastName: "Karryyeva",
      firstName: "Shirin",
      country: "tm",
      categoryList: "CHM-FP SBSTTA-FP CPB-CC",
      prefix: "Ms.",
      position: "Project Manager",
      organizationName: "Central Asian Desert Initiative (CADI) - Conservation and sustainable use of deserts in Turkmenistan",
     phone: "+993 12 45 120",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "168",
      email: "saparmuradovdzuma@gmail.com",
      "E-Mail 2": "mnptm.dcep@gmail.com",
      lastName: "Saparmyradov",
      firstName: "Jumamyrat",
      country: "tm",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR ABS-FP CPB-FP1",
      prefix: "Dr.",
      position: "Head",
      department: "Environment Protection and Hydrometeorology",
      organizationName: "Ministry of Agriculture and Environment Protection",
     phone: "+993 12 44 79 51",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "6491",
      email: "tilia.tima@gmail.com",
      lastName: "Tima",
      firstName: "Tilia",
      country: "tv",
      categoryList: "CHM-FP ABS-FP PA-FP",
      prefix: "Ms.",
      position: "Biodiversity Officer",
      organizationName: "Ministry of Public Works and Infrastructure, Environment, Labour, Meterology and Disaster",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "3222",
      email: "francis.ogwal@nema.go.ug",
      "E-Mail 2": "sabinofrancis@gmail.com",
      lastName: "Sabino Ogwal",
      firstName: "Francis Meri",
      country: "ug",
      categoryList: "CBD-FP1 CHM-FP CHM-NET CBD-NR SBSTTA-FP ABS-FP",
      prefix: "Mr.",
      position: "Natural Resources Manager (Biodiversity and Rangelands)",
      organizationName: "National Environment Management Authority (NEMA)",
     phone: "+256 414 251 064, 5, 8",
      unLang: "EN",
      mailOutLang: "E"
  },
  {
      id:  "4015",
      email: "yu.bondarenko@i.ua",
      "E-Mail 2": "yuliya.bondarenko@birdlife.org.ua",
      "E-Mail 3": "bondarenko@menr.gov.ua",
      lastName: "Bondarenko",
      firstName: "Yuliya",
      country: "ua",
      categoryList: "CHM-FP CHM-IAC CBD-NR",
      prefix: "Mrs.",
      position: "Chief Expert, Eco-Network and Biosafety Division",
      department: "Department of Natural Resources Protection, Eco-Network and Biosafety",
      organizationName: "Ministry of Environmental Protection and Natural Resources",
     phone: "+38 044 206 31 53",
      unLang: "RU-EN",
      mailOutLang: "R"
  },
  {
      id:  "3397",
      email: "environment@gov.ps",
      lastName: "Abu Safieh",
      firstName: "Yousef",
      categoryList: "CHM-FP",
      prefix: "H.E. Dr.",
      position: "Minister",
      organizationName: "Ministry of Environmental Affairs",
     phone: "+9708 2822000/2847208",
      organizationUrl: "http://www.mena.gov.ps/"
  }
]

export default focalPoints