version: '3.6'
services:
  web:
{{#unless isLocal}}
    resources:
      limits:
        cpus: 0.50
        memory: 512M
{{/unless}}
    labels:
      - traefik.enable=true
      ## HTTP Services
      - traefik.http.services.{{name}}-svc.loadbalancer.server.port=80

      ## Redirects
  {{#if site.redirectTo}}
    {{#each site.redirects as |rdr index|}}
      {{#each rdr as |from to|}}
      - traefik.http.middlewares.rdr-{{index}}.redirectregex.regex=^https://{{from}}/(.*)
      - traefik.http.middlewares.rdr-{{index}}.redirectregex.replacement=https://{{to}}/$${1}
      - traefik.http.middlewares.rdr-{{index}}.redirectregex.permanent=true

      - traefik.http.routers.rdr-{{index}}-rtr.entrypoints=https
      - traefik.http.routers.rdr-{{index}}-rtr.rule=Host(`{{from}}`)
      - traefik.http.routers.rdr-{{index}}-rtr.service=prod-svc
      - traefik.http.routers.rdr-{{index}}-rtr.priority=2
      - traefik.http.routers.rdr-{{index}}-rtr.middlewares=rdr-{{index}}
      {{/each}}
    {{/each}}
  {{/if}}

      ## HTTP Routers router.name = b-${branchName}-${subDomain}-${countryCode} // uniqure router definition via name
  {{#each sites as |site code|}}
    {{#if site.redirectTo}}
      ## {{code}} redirect base
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.entrypoints=https
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.rule=Host(`{{site.redirectTo}}`)
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.service={{../name}}-svc
      - traefik.http.routers.b-{{../name}}-{{code}}-redirect-base-rtr.priority={{../routePriority}}

    {{/if}}
    {{#each site.urlObjects as |urlObj index|}}
      {{#unless site.redirectTo}}
      ## {{code}} {{urlObj.url}}
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.rule=Host(`{{urlObj.url}}`)
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.service={{../../name}}-svc
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.priority={{../../routePriority}}

      {{/unless}}
      {{#if site.redirectTo}}
      ## {{code}} {{urlObj.url}} redirect to site.redirectTo
      - traefik.http.middlewares.b-{{../../name}}-{{code}}-{{index}}-mw.redirectregex.regex=https://^http://{{urlObj.url}}/(.*)
      - traefik.http.middlewares.b-{{../../name}}-{{code}}-{{index}}-mw.redirectregex.replacement=https://{{site.redirectTo}}$${1}
      - traefik.http.middlewares.b-{{../../name}}-{{code}}-{{index}}-mw.redirectregex.permanent=true

      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.entrypoints=https
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.rule=Host(`{{urlObj.url}}`)
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.service={{../../name}}-svc
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.priority=0
      - traefik.http.routers.b-{{../../name}}-{{code}}-{{index}}-rtr.middlewares=b-{{../../name}}-{{code}}-{{index}}-mw

      {{/if}}
    {{/each}}
  {{/each}}
    external_links:
      - loadbalancer_traefik_1
    networks:
      - webgateway
      - ddev_default
{{#unless isLocal}}
  db:
    deploy:
      resources:
          limits:
            cpus: 0.50
            memory: 1536M
    volumes:
      - source: /home/ubuntu/efs/archives
        target: /dumps
        type: bind
        volume:
          nocopy: true
{{/unless}}
networks:
  webgateway:
    external: true
  ddev_default:
    external: true